# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: homer-app
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

dist: release
scoop:
   commit_author:
     name: sipcapture_release
     email: alexandr.dubovikov@gmail.com
builds:
- env:
  - CGO_ENABLED=0
  ldflags: 
    - -s -w  
  goos:
      - linux
  goarch:
      - amd64
#      - arm64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
